"""Fix migration to prevent duplicate table

Revision ID: f23d79eeb851
Revises: 9ff3d4976ba7
Create Date: 2025-10-17 00:01:42.603830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f23d79eeb851'
down_revision = '9ff3d4976ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['tuition_requirement.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_registration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('mobile_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('tuition_requirement', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('tuition_requirement_tutor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tuition_requirement_student_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_registration', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'tutor_registration', ['tutor_id'], ['id'])
        batch_op.drop_column('pdf_filename')

    with op.batch_alter_table('tutor_profile', schema=None) as batch_op:
        batch_op.alter_column('subjects',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('tutor_profile_tutor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tutor_registration', ['tutor_id'], ['id'])

    with op.batch_alter_table('tutor_registration', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('mobile_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('mobile_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('tutor_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tutor_profile_tutor_id_fkey'), 'tutor_registration', ['tutor_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('subjects',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)

    with op.batch_alter_table('tuition_requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tuition_requirement_student_id_fkey'), 'student_registration', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('tuition_requirement_tutor_id_fkey'), 'tutor_profile', ['tutor_id'], ['id'])
        batch_op.alter_column('description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('mobile_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.drop_table('access_request')
    # ### end Alembic commands ###
